### ISSUE TITLE
Photos do not always fill view

### ISSUE THREAD

**Issue by justin-taylor** [jberlana/JBKenBurns#24]
I am having an issue where the animated photo will start in a position that leaves white space around the photo that is being animated. The animation usually moves the photo to fill the space. This happens regardless of the isLandscape flag.

I am using the version from cocoaPods.

**Comment by andr3a88** [comment]
I have the same problem with low-resolution images.
![ios simulator screen shot 05 giu 2015 10 55 13](https://cloud.githubusercontent.com/assets/6755254/8002741/9285e2b0-0b71-11e5-8759-7dfe289fc581.png)

**Comment by manonthemoon42** [comment]
I have the same problem. We should always check that the image is actually in the screen. 
I also have empty space sometimes.
