### ISSUE TITLE
Need to able to set zoom points

### ISSUE THREAD

**Issue by synapse-consulting** [jberlana/JBKenBurns#42]
I have a request for this project. This works very nice but it zooms at random places. I have a requirement where I need to zoom each image at some specific point and the user will be able to set that point.

Please let me know if this is possible.

Thanks.

**Comment by jberlana** [comment]
The library is not able to do that, but if you wrote the feature do not hesitate to send a pull request :)

**Comment by synapse-consulting** [comment]
Yeah sure I will.
